export const ADD_NEW_PERSON = 'ADD_NEW_PERSON'
export const FETCH_PERSONS = 'FETCH_PERSONS'
export const CHANGE_ACTIVE_PERSON = 'CHANGE_ACTIVE_PERSON'
export const DELETE_PERSON='DELETE_PERSON'
export const EDIT_PERSON='EDIT_PERSON'
export const CHANGE_EDIT='CHANGE_EDIT'
export const CHANGE_DELETE='CHANGE_DELETE'

export const FETCH_POSTS='FETCH_POSTS'
export const ADD_NEW_POST='ADD_NEW_POST'
export const CHANGE_EDIT_POST='CHANGE_EDIT_POST'

export const FETCH_ALBUMS='FETCH_ALBUMS'
export const ADD_NEW_ALBUM='ADD_NEW_ALBUM'
export const CHANGE_EDIT_ALBUM='CHANGE_EDIT_ALBUM'


export const FETCH_PHOTOS='FETCH_PHOTOS'
export const ADD_NEW_PHOTO='ADD_NEW_PHOTO'
export const CHANGE_EDIT_PHOTO='CHANGE_EDIT_PHOTO'
export const ADD_LIKE='ADD_LIKE'

export const FETCH_COMMENTS='FETCH_COMMENTS'
export const ADD_NEW_COMMENT='ADD_NEW_COMMENT'
export const CHANGE_EDIT_COMMENTS='CHANGE_EDIT_COMMENTS'